2021-04-10 16:11:48 - main.py - INFO - frp support started
2021-04-10 16:11:48 - start_frp.py - INFO - b'2021/04/10 16:11:48 [I] [service.go:304] [3bb68a7f54430220] login to server success, get run id [3bb68a7f54430220], server udp port [0]\n'
2021-04-10 16:11:48 - start_frp.py - INFO - b'2021/04/10 16:11:48 [I] [proxy_manager.go:144] [3bb68a7f54430220] proxy added: [RDPDEEPIN]\n'
2021-04-10 16:11:48 - start_frp.py - INFO - b'2021/04/10 16:11:48 [I] [control.go:180] [3bb68a7f54430220] [RDPDEEPIN] start proxy success\n'
2021-04-10 16:12:38 - start_frp.py - INFO - b'2021/04/10 16:12:38 [I] [control.go:282] [3bb68a7f54430220] control writer is closing\n'
2021-04-10 16:12:38 - start_frp.py - INFO - b'2021/04/10 16:12:38 [E] [control.go:158] [3bb68a7f54430220] work connection closed before response StartWorkConn message: EOF\n'
2021-04-10 16:12:38 - start_frp.py - INFO - b'2021/04/10 16:12:38 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:38 - start_frp.py - INFO - b'2021/04/10 16:12:38 [I] [visitor_manager.go:60] [3bb68a7f54430220] gracefully shutdown visitor manager\n'
2021-04-10 16:12:38 - start_frp.py - INFO - b'2021/04/10 16:12:38 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:39 - start_frp.py - INFO - b'2021/04/10 16:12:39 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:39 - start_frp.py - INFO - b'2021/04/10 16:12:39 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:41 - start_frp.py - INFO - b'2021/04/10 16:12:41 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:41 - start_frp.py - INFO - b'2021/04/10 16:12:41 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:43 - start_frp.py - INFO - b'2021/04/10 16:12:43 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:43 - start_frp.py - INFO - b'2021/04/10 16:12:43 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:45 - start_frp.py - INFO - b'2021/04/10 16:12:45 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:45 - start_frp.py - INFO - b'2021/04/10 16:12:45 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:47 - start_frp.py - INFO - b'2021/04/10 16:12:47 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:47 - start_frp.py - INFO - b'2021/04/10 16:12:47 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:49 - start_frp.py - INFO - b'2021/04/10 16:12:49 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:49 - start_frp.py - INFO - b'2021/04/10 16:12:49 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:51 - start_frp.py - INFO - b'2021/04/10 16:12:51 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:51 - start_frp.py - INFO - b'2021/04/10 16:12:51 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:53 - start_frp.py - INFO - b'2021/04/10 16:12:53 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:53 - start_frp.py - INFO - b'2021/04/10 16:12:53 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:55 - start_frp.py - INFO - b'2021/04/10 16:12:55 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:55 - start_frp.py - INFO - b'2021/04/10 16:12:55 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:57 - start_frp.py - INFO - b'2021/04/10 16:12:57 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:57 - start_frp.py - INFO - b'2021/04/10 16:12:57 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:12:59 - start_frp.py - INFO - b'2021/04/10 16:12:59 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:12:59 - start_frp.py - INFO - b'2021/04/10 16:12:59 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:01 - start_frp.py - INFO - b'2021/04/10 16:13:01 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:01 - start_frp.py - INFO - b'2021/04/10 16:13:01 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:03 - start_frp.py - INFO - b'2021/04/10 16:13:03 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:03 - start_frp.py - INFO - b'2021/04/10 16:13:03 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:05 - start_frp.py - INFO - b'2021/04/10 16:13:05 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:05 - start_frp.py - INFO - b'2021/04/10 16:13:05 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:07 - start_frp.py - INFO - b'2021/04/10 16:13:07 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:07 - start_frp.py - INFO - b'2021/04/10 16:13:07 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:09 - start_frp.py - INFO - b'2021/04/10 16:13:09 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:09 - start_frp.py - INFO - b'2021/04/10 16:13:09 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:11 - start_frp.py - INFO - b'2021/04/10 16:13:11 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:11 - start_frp.py - INFO - b'2021/04/10 16:13:11 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:13 - start_frp.py - INFO - b'2021/04/10 16:13:13 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:13 - start_frp.py - INFO - b'2021/04/10 16:13:13 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:15 - start_frp.py - INFO - b'2021/04/10 16:13:15 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:15 - start_frp.py - INFO - b'2021/04/10 16:13:15 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:17 - start_frp.py - INFO - b'2021/04/10 16:13:17 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:17 - start_frp.py - INFO - b'2021/04/10 16:13:17 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:19 - start_frp.py - INFO - b'2021/04/10 16:13:19 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:19 - start_frp.py - INFO - b'2021/04/10 16:13:19 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:21 - start_frp.py - INFO - b'2021/04/10 16:13:21 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:21 - start_frp.py - INFO - b'2021/04/10 16:13:21 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:23 - start_frp.py - INFO - b'2021/04/10 16:13:23 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:23 - start_frp.py - INFO - b'2021/04/10 16:13:23 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:25 - start_frp.py - INFO - b'2021/04/10 16:13:25 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:25 - start_frp.py - INFO - b'2021/04/10 16:13:25 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:27 - start_frp.py - INFO - b'2021/04/10 16:13:27 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:27 - start_frp.py - INFO - b'2021/04/10 16:13:27 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:29 - start_frp.py - INFO - b'2021/04/10 16:13:29 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:29 - start_frp.py - INFO - b'2021/04/10 16:13:29 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:31 - start_frp.py - INFO - b'2021/04/10 16:13:31 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:31 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:33 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:33 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:35 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:35 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:37 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:37 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:39 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:39 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:41 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:41 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:43 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:43 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:45 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:45 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:47 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:47 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:49 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:50 - start_frp.py - INFO - b'2021/04/10 16:13:49 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:13:51 - start_frp.py - INFO - b'2021/04/10 16:13:51 [I] [service.go:177] [3bb68a7f54430220] try to reconnect to server...\n'
2021-04-10 16:13:51 - start_frp.py - INFO - b'2021/04/10 16:13:51 [W] [service.go:180] [3bb68a7f54430220] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:16:26 - main.py - INFO - frp support started
2021-04-10 16:16:26 - main.py - INFO -  frp started
2021-04-10 16:16:26 - main.py - INFO - start check network
2021-04-10 16:16:26 - net_util.py - INFO - connect success
2021-04-10 16:16:56 - net_util.py - INFO - connect success
2021-04-10 16:17:13 - main.py - INFO - frp support started
2021-04-10 16:17:28 - main.py - INFO - frp support started
2021-04-10 16:17:28 - main.py - INFO -  frp started
2021-04-10 16:17:28 - main.py - INFO - start check network
2021-04-10 16:17:28 - net_util.py - INFO - connect success
2021-04-10 16:17:28 - start_frp.py - INFO - b'2021/04/10 16:17:28 [I] [service.go:304] [92e109cb7fd90db3] login to server success, get run id [92e109cb7fd90db3], server udp port [0]\n'
2021-04-10 16:17:28 - start_frp.py - INFO - b'2021/04/10 16:17:28 [I] [proxy_manager.go:144] [92e109cb7fd90db3] proxy added: [RDPDEEPIN]\n'
2021-04-10 16:17:29 - start_frp.py - INFO - b'2021/04/10 16:17:29 [I] [control.go:180] [92e109cb7fd90db3] [RDPDEEPIN] start proxy success\n'
2021-04-10 16:17:58 - net_util.py - INFO - connect success
2021-04-10 16:18:28 - net_util.py - ERROR - connect socket error
2021-04-10 16:20:12 - main.py - INFO - frp support started
2021-04-10 16:20:12 - main.py - INFO -  frp started
2021-04-10 16:20:12 - main.py - INFO - start check network
2021-04-10 16:20:12 - net_util.py - ERROR - connect socket error
2021-04-10 16:20:12 - net_util.py - INFO - start network change
2021-04-10 16:20:12 - start_frp.py - INFO - b'2021/04/10 16:20:12 [W] [service.go:104] login to server failed: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:20:12 - start_frp.py - INFO - b'dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:20:12 - net_util.py - INFO - 0
2021-04-10 16:20:12 - net_util.py - INFO - network change end
2021-04-10 16:20:22 - start_frp.py - ERROR - []
2021-04-10 16:20:22 - start_frp.py - ERROR - 1
2021-04-10 16:20:54 - net_util.py - ERROR - connect socket error
2021-04-10 16:21:24 - net_util.py - INFO - connect success
2021-04-10 16:21:54 - net_util.py - ERROR - connect socket error
2021-04-10 16:22:09 - net_util.py - INFO - start network change
2021-04-10 16:22:10 - net_util.py - INFO - 0
2021-04-10 16:22:10 - net_util.py - INFO - network change end
2021-04-10 16:29:27 - net_util.py - ERROR - connect socket error
2021-04-10 16:31:08 - net_util.py - ERROR - connect socket error
2021-04-10 16:31:17 - net_util.py - INFO - start network change
2021-04-10 16:31:17 - net_util.py - INFO - 0
2021-04-10 16:31:17 - net_util.py - INFO - network change end
2021-04-10 16:31:59 - net_util.py - ERROR - connect socket error
2021-04-10 16:32:37 - net_util.py - INFO - connect success
2021-04-10 16:32:59 - main.py - INFO - frp support started
2021-04-10 16:32:59 - main.py - INFO -  frp started
2021-04-10 16:32:59 - main.py - INFO - start check network
2021-04-10 16:32:59 - net_util.py - INFO - connect success
2021-04-10 16:32:59 - start_frp.py - INFO - b'2021/04/10 16:32:59 [I] [service.go:304] [2df9a2f7cb74b8b0] login to server success, get run id [2df9a2f7cb74b8b0], server udp port [0]\n'
2021-04-10 16:32:59 - start_frp.py - INFO - b'2021/04/10 16:32:59 [I] [proxy_manager.go:144] [2df9a2f7cb74b8b0] proxy added: [RDPDEEPIN]\n'
2021-04-10 16:32:59 - start_frp.py - INFO - b'2021/04/10 16:32:59 [I] [control.go:180] [2df9a2f7cb74b8b0] [RDPDEEPIN] start proxy success\n'
2021-04-10 16:33:29 - net_util.py - INFO - connect success
2021-04-10 16:33:59 - net_util.py - INFO - connect success
2021-04-10 16:34:30 - net_util.py - INFO - connect success
2021-04-10 16:34:50 - start_frp.py - INFO - b'2021/04/10 16:34:50 [E] [control.go:158] [2df9a2f7cb74b8b0] work connection closed before response StartWorkConn message: EOF\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:50 [I] [control.go:282] [2df9a2f7cb74b8b0] control writer is closing\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:50 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:50 [I] [visitor_manager.go:60] [2df9a2f7cb74b8b0] gracefully shutdown visitor manager\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:50 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:51 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:51 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:53 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:53 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:55 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:55 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:57 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:57 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:59 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:34:59 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:35:01 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:35:01 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:35:03 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:35:03 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:35:05 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:35:05 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:35:07 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:08 - start_frp.py - INFO - b'2021/04/10 16:35:07 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:09 - start_frp.py - INFO - b'2021/04/10 16:35:09 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:09 - start_frp.py - INFO - b'2021/04/10 16:35:09 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:11 - start_frp.py - INFO - b'2021/04/10 16:35:11 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:11 - start_frp.py - INFO - b'2021/04/10 16:35:11 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:13 - start_frp.py - INFO - b'2021/04/10 16:35:13 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:13 - start_frp.py - INFO - b'2021/04/10 16:35:13 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:15 - start_frp.py - INFO - b'2021/04/10 16:35:15 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:15 - start_frp.py - INFO - b'2021/04/10 16:35:15 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:17 - start_frp.py - INFO - b'2021/04/10 16:35:17 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:17 - start_frp.py - INFO - b'2021/04/10 16:35:17 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:19 - start_frp.py - INFO - b'2021/04/10 16:35:19 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:19 - start_frp.py - INFO - b'2021/04/10 16:35:19 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:21 - start_frp.py - INFO - b'2021/04/10 16:35:21 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:21 - start_frp.py - INFO - b'2021/04/10 16:35:21 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:23 - start_frp.py - INFO - b'2021/04/10 16:35:23 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:23 - start_frp.py - INFO - b'2021/04/10 16:35:23 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:25 - start_frp.py - INFO - b'2021/04/10 16:35:25 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:25 - start_frp.py - INFO - b'2021/04/10 16:35:25 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:27 - start_frp.py - INFO - b'2021/04/10 16:35:27 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:27 - start_frp.py - INFO - b'2021/04/10 16:35:27 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:29 - start_frp.py - INFO - b'2021/04/10 16:35:29 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:29 - start_frp.py - INFO - b'2021/04/10 16:35:29 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:31 - start_frp.py - INFO - b'2021/04/10 16:35:31 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:31 - start_frp.py - INFO - b'2021/04/10 16:35:31 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:33 - start_frp.py - INFO - b'2021/04/10 16:35:33 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:33 - start_frp.py - INFO - b'2021/04/10 16:35:33 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:35 - start_frp.py - INFO - b'2021/04/10 16:35:35 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:35 - start_frp.py - INFO - b'2021/04/10 16:35:35 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:37 - start_frp.py - INFO - b'2021/04/10 16:35:37 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:37 - start_frp.py - INFO - b'2021/04/10 16:35:37 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable host.\n'
2021-04-10 16:35:38 - net_util.py - ERROR - connect socket error
2021-04-10 16:35:38 - net_util.py - INFO - start network change
2021-04-10 16:35:38 - net_util.py - INFO - 0
2021-04-10 16:35:38 - net_util.py - INFO - network change end
2021-04-10 16:35:39 - start_frp.py - INFO - b'2021/04/10 16:35:39 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:39 - start_frp.py - INFO - b'2021/04/10 16:35:39 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:35:41 - start_frp.py - INFO - b'2021/04/10 16:35:41 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:41 - start_frp.py - INFO - b'2021/04/10 16:35:41 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:35:43 - start_frp.py - INFO - b'2021/04/10 16:35:43 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:43 - start_frp.py - INFO - b'2021/04/10 16:35:43 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:35:45 - start_frp.py - INFO - b'2021/04/10 16:35:45 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:35:45 - start_frp.py - INFO - b'2021/04/10 16:35:45 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:35:47 - start_frp.py - INFO - b'2021/04/10 16:35:47 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:36:08 - start_frp.py - INFO - b'2021/04/10 16:36:08 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:36:10 - start_frp.py - INFO - b'2021/04/10 16:36:10 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:36:20 - net_util.py - ERROR - connect socket error
2021-04-10 16:36:31 - start_frp.py - INFO - b'2021/04/10 16:36:31 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:36:33 - start_frp.py - INFO - b'2021/04/10 16:36:33 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:36:50 - net_util.py - INFO - connect success
2021-04-10 16:36:54 - start_frp.py - INFO - b'2021/04/10 16:36:54 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:36:58 - start_frp.py - INFO - b'2021/04/10 16:36:56 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:37:17 - start_frp.py - INFO - b'2021/04/10 16:37:17 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:37:19 - start_frp.py - INFO - b'2021/04/10 16:37:19 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:37:35 - net_util.py - INFO - connect success
2021-04-10 16:37:40 - start_frp.py - INFO - b'2021/04/10 16:37:40 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:37:42 - start_frp.py - INFO - b'2021/04/10 16:37:42 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:38:03 - start_frp.py - INFO - b'2021/04/10 16:38:03 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:38:05 - start_frp.py - INFO - b'2021/04/10 16:38:05 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:38:05 - net_util.py - ERROR - connect socket error
2021-04-10 16:38:05 - net_util.py - INFO - start network change
2021-04-10 16:38:05 - net_util.py - INFO - 0
2021-04-10 16:38:05 - net_util.py - INFO - network change end
2021-04-10 16:38:06 - start_frp.py - INFO - b'2021/04/10 16:38:06 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: An established connection was aborted by the software in your host machine.\n'
2021-04-10 16:38:08 - start_frp.py - INFO - b'2021/04/10 16:38:08 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:38:08 - start_frp.py - INFO - b'2021/04/10 16:38:08 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:38:10 - start_frp.py - INFO - b'2021/04/10 16:38:10 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:38:10 - start_frp.py - INFO - b'2021/04/10 16:38:10 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:38:12 - start_frp.py - INFO - b'2021/04/10 16:38:12 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:38:33 - start_frp.py - INFO - b'2021/04/10 16:38:33 [W] [service.go:180] [2df9a2f7cb74b8b0] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:38:35 - start_frp.py - INFO - b'2021/04/10 16:38:35 [I] [service.go:177] [2df9a2f7cb74b8b0] try to reconnect to server...\n'
2021-04-10 16:38:58 - main.py - INFO - frp support started
2021-04-10 16:38:58 - main.py - INFO -  frp started
2021-04-10 16:38:58 - main.py - INFO - start check network
2021-04-10 16:38:58 - net_util.py - ERROR - connect socket error
2021-04-10 16:38:58 - net_util.py - INFO - start network change
2021-04-10 16:38:59 - net_util.py - INFO - 0
2021-04-10 16:38:59 - net_util.py - INFO - network change end
2021-04-10 16:38:59 - start_frp.py - INFO - b'2021/04/10 16:38:59 [W] [service.go:104] login to server failed: dial tcp 13.75.7.171:7000: connectex: An established connection was aborted by the software in your host machine.\n'
2021-04-10 16:38:59 - start_frp.py - INFO - b'dial tcp 13.75.7.171:7000: connectex: An established connection was aborted by the software in your host machine.\n'
2021-04-10 16:39:09 - start_frp.py - ERROR - []
2021-04-10 16:39:09 - start_frp.py - ERROR - 1
2021-04-10 16:39:34 - main.py - INFO - frp support started
2021-04-10 16:39:34 - main.py - INFO -  frp started
2021-04-10 16:39:34 - main.py - INFO - start check network
2021-04-10 16:39:46 - net_util.py - ERROR - connect socket error
2021-04-10 16:39:46 - net_util.py - INFO - start network change
2021-04-10 16:39:47 - net_util.py - INFO - 0
2021-04-10 16:39:47 - net_util.py - INFO - network change end
2021-04-10 16:39:47 - start_frp.py - INFO - b'2021/04/10 16:39:47 [W] [service.go:104] login to server failed: dial tcp 13.75.7.171:7000: connectex: An established connection was aborted by the software in your host machine.\n'
2021-04-10 16:39:47 - start_frp.py - INFO - b'dial tcp 13.75.7.171:7000: connectex: An established connection was aborted by the software in your host machine.\n'
2021-04-10 16:39:57 - start_frp.py - ERROR - []
2021-04-10 16:39:57 - start_frp.py - ERROR - 1
2021-04-10 16:40:06 - main.py - INFO - frp support started
2021-04-10 16:40:06 - main.py - INFO -  frp started
2021-04-10 16:40:06 - main.py - INFO - start check network
2021-04-10 16:40:18 - net_util.py - ERROR - connect socket error
2021-04-10 16:40:18 - net_util.py - INFO - start network change
2021-04-10 16:40:18 - net_util.py - INFO - 0
2021-04-10 16:40:18 - net_util.py - INFO - network change end
2021-04-10 16:40:18 - start_frp.py - INFO - b'2021/04/10 16:40:18 [W] [service.go:104] login to server failed: dial tcp 13.75.7.171:7000: connectex: An established connection was aborted by the software in your host machine.\n'
2021-04-10 16:40:18 - start_frp.py - INFO - b'dial tcp 13.75.7.171:7000: connectex: An established connection was aborted by the software in your host machine.\n'
2021-04-10 16:40:28 - start_frp.py - ERROR - []
2021-04-10 16:40:43 - start_frp.py - ERROR - 1
2021-04-10 16:44:25 - main.py - INFO - frp support started
2021-04-10 16:44:25 - main.py - INFO -  frp started
2021-04-10 16:44:25 - main.py - INFO - start check network
2021-04-10 16:44:25 - net_util.py - INFO - connect success
2021-04-10 16:44:25 - start_frp.py - INFO - b'2021/04/10 16:44:25 [I] [service.go:304] [d75cab360db042c6] login to server success, get run id [d75cab360db042c6], server udp port [0]\n'
2021-04-10 16:44:25 - start_frp.py - INFO - b'2021/04/10 16:44:25 [I] [proxy_manager.go:144] [d75cab360db042c6] proxy added: [RDPDEEPIN]\n'
2021-04-10 16:44:25 - start_frp.py - INFO - b'2021/04/10 16:44:25 [I] [control.go:180] [d75cab360db042c6] [RDPDEEPIN] start proxy success\n'
2021-04-10 16:44:55 - net_util.py - ERROR - connect socket error
2021-04-10 16:44:55 - net_util.py - INFO - start network change
2021-04-10 16:44:56 - net_util.py - INFO - 0
2021-04-10 16:44:56 - net_util.py - INFO - network change end
2021-04-10 16:45:00 - start_frp.py - INFO - b'2021/04/10 16:45:00 [E] [control.go:158] [d75cab360db042c6] work connection closed before response StartWorkConn message: EOF\n'
2021-04-10 16:45:00 - start_frp.py - INFO - b'2021/04/10 16:45:00 [I] [control.go:282] [d75cab360db042c6] control writer is closing\n'
2021-04-10 16:45:00 - start_frp.py - INFO - b'2021/04/10 16:45:00 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:45:00 - start_frp.py - INFO - b'2021/04/10 16:45:00 [I] [visitor_manager.go:60] [d75cab360db042c6] gracefully shutdown visitor manager\n'
2021-04-10 16:45:00 - start_frp.py - INFO - b'2021/04/10 16:45:00 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:45:01 - start_frp.py - INFO - b'2021/04/10 16:45:01 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:45:01 - start_frp.py - INFO - b'2021/04/10 16:45:01 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:45:03 - start_frp.py - INFO - b'2021/04/10 16:45:03 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:45:03 - start_frp.py - INFO - b'2021/04/10 16:45:03 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:45:05 - start_frp.py - INFO - b'2021/04/10 16:45:05 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:45:05 - start_frp.py - INFO - b'2021/04/10 16:45:05 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:45:07 - start_frp.py - INFO - b'2021/04/10 16:45:07 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:45:07 - start_frp.py - INFO - b'2021/04/10 16:45:07 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:45:09 - start_frp.py - INFO - b'2021/04/10 16:45:09 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:45:30 - start_frp.py - INFO - b'2021/04/10 16:45:30 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:45:32 - start_frp.py - INFO - b'2021/04/10 16:45:32 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:45:38 - net_util.py - ERROR - connect socket error
2021-04-10 16:45:53 - start_frp.py - INFO - b'2021/04/10 16:45:53 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:45:55 - start_frp.py - INFO - b'2021/04/10 16:45:55 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:45:56 - start_frp.py - INFO - b'2021/04/10 16:45:56 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: An established connection was aborted by the software in your host machine.\n'
2021-04-10 16:45:58 - start_frp.py - INFO - b'2021/04/10 16:45:58 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:45:58 - start_frp.py - INFO - b'2021/04/10 16:45:58 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:46:00 - start_frp.py - INFO - b'2021/04/10 16:46:00 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:46:00 - start_frp.py - INFO - b'2021/04/10 16:46:00 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:46:02 - start_frp.py - INFO - b'2021/04/10 16:46:02 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:46:20 - net_util.py - ERROR - connect socket error
2021-04-10 16:46:20 - net_util.py - INFO - start network change
2021-04-10 16:46:20 - net_util.py - INFO - 0
2021-04-10 16:46:20 - net_util.py - INFO - network change end
2021-04-10 16:46:21 - start_frp.py - INFO - b'2021/04/10 16:46:21 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: An established connection was aborted by the software in your host machine.\n'
2021-04-10 16:46:23 - start_frp.py - INFO - b'2021/04/10 16:46:23 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:46:23 - start_frp.py - INFO - b'2021/04/10 16:46:23 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:46:25 - start_frp.py - INFO - b'2021/04/10 16:46:25 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:46:25 - start_frp.py - INFO - b'2021/04/10 16:46:25 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A socket operation was attempted to an unreachable network.\n'
2021-04-10 16:46:27 - start_frp.py - INFO - b'2021/04/10 16:46:27 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:46:48 - start_frp.py - INFO - b'2021/04/10 16:46:48 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:47:02 - net_util.py - ERROR - connect socket error
2021-04-10 16:47:18 - start_frp.py - INFO - b'2021/04/10 16:46:50 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:47:18 - start_frp.py - INFO - b'2021/04/10 16:47:11 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:47:18 - start_frp.py - INFO - b'2021/04/10 16:47:13 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:47:34 - start_frp.py - INFO - b'2021/04/10 16:47:34 [W] [service.go:180] [d75cab360db042c6] reconnect to server error: dial tcp 13.75.7.171:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\n'
2021-04-10 16:47:36 - start_frp.py - INFO - b'2021/04/10 16:47:36 [I] [service.go:177] [d75cab360db042c6] try to reconnect to server...\n'
2021-04-10 16:47:37 - start_frp.py - INFO - b'2021/04/10 16:47:37 [I] [service.go:304] [d75cab360db042c6] login to server success, get run id [d75cab360db042c6], server udp port [0]\n'
2021-04-10 16:47:37 - start_frp.py - INFO - b'2021/04/10 16:47:37 [I] [proxy_manager.go:144] [d75cab360db042c6] proxy added: [RDPDEEPIN]\n'
2021-04-10 16:47:37 - start_frp.py - INFO - b'2021/04/10 16:47:37 [I] [control.go:180] [d75cab360db042c6] [RDPDEEPIN] start proxy success\n'
2021-04-10 16:47:48 - net_util.py - INFO - connect success
2021-04-10 16:48:18 - net_util.py - INFO - connect success
2021-04-10 16:48:48 - net_util.py - INFO - connect success
2021-04-10 16:49:18 - net_util.py - INFO - connect success
2021-04-10 16:49:48 - net_util.py - INFO - connect success
2021-04-10 16:50:18 - net_util.py - INFO - connect success
2021-04-10 16:50:48 - net_util.py - INFO - connect success
2021-04-10 16:51:18 - net_util.py - INFO - connect success
2021-04-10 16:51:48 - net_util.py - INFO - connect success
2021-04-10 16:52:18 - net_util.py - INFO - connect success
2021-04-10 16:52:48 - net_util.py - INFO - connect success
2021-04-10 16:53:18 - net_util.py - INFO - connect success
2021-04-10 16:53:48 - net_util.py - INFO - connect success
2021-04-10 16:54:18 - net_util.py - INFO - connect success
2021-04-10 16:54:49 - net_util.py - INFO - connect success
2021-04-10 16:55:19 - net_util.py - INFO - connect success
2021-04-10 16:55:49 - net_util.py - INFO - connect success
2021-04-10 16:56:19 - net_util.py - INFO - connect success
2021-04-10 16:56:49 - net_util.py - INFO - connect success
2021-04-10 16:57:19 - net_util.py - INFO - connect success
2021-04-10 16:57:49 - net_util.py - INFO - connect success
2021-04-10 16:58:19 - net_util.py - INFO - connect success
2021-04-10 16:58:49 - net_util.py - INFO - connect success
2021-04-10 16:59:19 - net_util.py - INFO - connect success
2021-04-10 16:59:49 - net_util.py - INFO - connect success
2021-04-10 17:00:19 - net_util.py - INFO - connect success
2021-04-10 17:00:49 - net_util.py - INFO - connect success
2021-04-10 17:01:19 - net_util.py - INFO - connect success
2021-04-10 17:01:49 - net_util.py - INFO - connect success
2021-04-10 17:02:19 - net_util.py - INFO - connect success
2021-04-10 17:02:49 - net_util.py - INFO - connect success
2021-04-10 17:03:20 - net_util.py - INFO - connect success
2021-04-10 17:03:50 - net_util.py - INFO - connect success
2021-04-10 17:04:20 - net_util.py - INFO - connect success
2021-04-10 17:04:50 - net_util.py - INFO - connect success
2021-04-10 17:05:20 - net_util.py - INFO - connect success
2021-04-10 17:05:50 - net_util.py - INFO - connect success
2021-04-10 17:06:20 - net_util.py - INFO - connect success
2021-04-10 17:06:50 - net_util.py - INFO - connect success
2021-04-10 17:07:20 - net_util.py - INFO - connect success
2021-04-10 17:07:50 - net_util.py - INFO - connect success
2021-04-10 17:08:20 - net_util.py - INFO - connect success
2021-04-10 17:08:50 - net_util.py - INFO - connect success
2021-04-10 17:09:20 - net_util.py - INFO - connect success
2021-04-10 17:09:50 - net_util.py - INFO - connect success
2021-04-10 17:10:21 - net_util.py - INFO - connect success
2021-04-10 17:10:51 - net_util.py - INFO - connect success
2021-04-10 17:11:21 - net_util.py - INFO - connect success
2021-04-10 17:11:51 - net_util.py - INFO - connect success
2021-04-10 17:12:21 - net_util.py - INFO - connect success
